### ISSUE TITLE
Write xmldocs for code

### ISSUE THREAD

**Issue by 0xdeafcafe** [branch-app/app-home#62]
Splitting this up into chunks, to make it seem less fucking horrific.
- [ ] **Branch.Helpers** :: Converters
- [x] **Branch.Helpers** :: Database
- [ ] **Branch.Helpers** :: DocumentDb
- [ ] **Branch.Helpers** :: Extensions
- [ ] **Branch.Helpers** :: Services
- [ ] **Branch.Service.Halo4** :: Database
- [ ] **Branch.Service.Halo4** :: DocumentDb
- [ ] **Branch.Service.Halo4** :: Exceptions
- [ ] **Branch.Service.Halo4** :: Extensions
- [ ] **Branch.Service.Halo4** :: Models
- [ ] **Branch.Service.Halo4** :: Services
- [ ] **Branch.Service.XboxLive** :: Database
- [ ] **Branch.Service.XboxLive** :: DocumentDb
- [ ] **Branch.Service.XboxLive** :: Extensions
- [ ] **Branch.Service.XboxLive** :: Services
- [ ] **Branch.Service.Xuid** :: Database
- [ ] **Branch.Service.Xuid** :: Exceptions
- [ ] **Branch.Service.Xuid** :: Extensions
- [ ] **Branch.Service.Xuid** :: Models
- [ ] **Branch.Service.Xuid** :: Services

And for the love of god, please write docs as I go from now on. This isn't going to be fun...

**Comment by kfwls** [comment]
ghostdoc -> format all. :^) The auto-genned ones suck on their own, but it does save some time.
